const styles = theme => ({
  container: {
    width: `${500 * 3 + 24 * 3}px`,
    maxWidth: '100%',
    marginLeft: 'auto',
    marginRight: 'auto',
    padding: '8px 12px 40px',
    display: 'flex',
  },
  nextDrawCard: {
    background: '#393960',
    border: '1px solid #4C4C80',
    borderRadius: '10px',
    width: '500px',
    padding: '24px',
    maxWidth: '100%',
  },
  nextDrawInner: {
    display: 'flex',
    width: '100%',
    marginBottom: '24px',
  },
  nextDrawPrizeText: {
    fontWeight: 500,
    fontSize: '15px',
    lineHeight: '24px',
    marginBottom: '12px',
    color: '#EBF3F9',
    textTransform: 'uppercase',
    '& span': {
      color: '#F3BA2E',
    },
  },
  nextDrawTimeContainer: {
    display: 'flex',
  },
  nextDrawTimeValue: {
    padding: '4px',
    border: '2px solid #F3BA2E',
    borderRadius: '4px',
    fontSize: '24px',
    lineHeight: '28px',
    fontWeight: 700,
    width: '48px',
    height: '40px',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  nextDrawTimeLabel: {
    fontSize: '10px',
    lineHeight: '20px',
    fontWeight: 700,
    color: '#FFFFFF',
    width: '48px',
    textAlign: 'center',
    padding: '2px 0',
  },
  nextDrawTimeSeparator: {
    fontSize: '24px',
    lineHeight: '24px',
    height: '40px',
    padding: '8px',
    color: '#FFFFFF',
  },
  nextDrawLogoContainer: {
    marginRight: '0',
    marginLeft: 'auto',
  },
  statsCard: {
    background: '#303050',
    border: '1px solid #4C4C80',
    borderRadius: '10px',
    width: '800px',
    padding: '24px',
    maxWidth: '100%',
    height: 'inherit',
    marginRight: '0px',
    marginLeft: 'auto',
    display: 'flex',
  },
  statsCardLabel: {
    fontWeight: 700,
    fontSize: '12px',
    lineHeight: '14px',
    color: '#8585A6',
    marginBottom: '8px',
  },
  statsCardValue: {
    fontWeight: 700,
    fontSize: '24px',
    lineHeight: '28px',
    color: '#FFFFFF',
  },
  statsVertCenterOuter: {
    position: 'relative',
  },
  statsVertCenterInner: {
    position: 'absolute',
    top: '50%',
    transform: 'translate(0,-50%)',
  },
});

export default styles;
